USE recipelookup;
DROP TABLE IF EXISTS USER_RECIPES;
DROP TABLE IF EXISTS USER_DIET_ALLERGY;
DROP TABLE IF EXISTS USER_ACCOUNTS;
CREATE TABLE USER_ACCOUNTS (
	userid VARCHAR(20),
    passkey VARCHAR(20),
    email VARCHAR(50),
    PRIMARY KEY (userid)
);

CREATE TABLE USER_DIET_ALLERGY (
	userid VARCHAR(20),
	FOREIGN KEY (userid) REFERENCES USER_ACCOUNTS(userid),
    diet SET('None', 'VEGETARIAN', 'VEGAN', 'PESKITARIAN'),
    allergy SET('MILK', 'SHELLFISH', 'GLUTEN', 'NUTS')
);

CREATE TABLE USER_RECIPES (
	userid VARCHAR(20),
    FOREIGN KEY (userid) REFERENCES USER_ACCOUNTS(userid),
    RECIPES VARCHAR(200)
);

INSERT INTO USER_ACCOUNTS VALUES ('example1', 'example1', 'example1@msudenver.edu');
INSERT INTO USER_ACCOUNTS VALUES ('example2', 'example2', 'example2@msudenver.edu');
INSERT INTO USER_ACCOUNTS VALUES ('example3', 'example3', 'example3@msudenver.edu');
INSERT INTO USER_ACCOUNTS VALUES ('example4', 'example4', 'example4@msudenver.edu');

INSERT INTO USER_DIET_ALLERGY VALUES ('example1', NULL, NULL);
INSERT INTO USER_DIET_ALLERGY VALUES ('example2', 'VEGAN', NULL);
INSERT INTO USER_DIET_ALLERGY VALUES ('example3', NULL, 'MILK');
INSERT INTO USER_DIET_ALLERGY (userid, diet, allergy) VALUES ('example1', 'VEGAN,VEGETARIAN', 'GLUTEN,NUTS');